services:
  web:
    container_name: web-flask
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    networks:
      - qdrant_bridge
    environment:
      - QDRANT_HOST=jovial_kapitsa
      - QDRANT_PORT=6333
      - COLLECTION_NAME=Gruppo1

  angular:
    container_name: angular-app
    build:
      context: ../web-ui-applicazioni-indusriali
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - qdrant_bridge

    
  agente:
    container_name: agente
    build:
      context: ../arxiv-summary-agent
      dockerfile: Dockerfile
    ports:
      - "5002:8000"
    networks:
      - qdrant_bridge

# This network already exists and contains the qdrant container.
# The port to be selected is before the docker port-forwarding.
networks:
  qdrant_bridge:
    external: true