services:
  web:
    container_name: agent-fastapi
    hostname: agent-fastapi
    image: agent-code-fastapi
    build:
      context: ../arxiv-summary-agent
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./temp:/app/temp
    networks:
      - qdrant_bridge
    environment:
      - QDRANT_HOST=jovial_kapitsa
      - QDRANT_PORT=6333
      - COLLECTION_NAME=Gruppo1
      - PYTHONUNBUFFERED=1
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}

  angular:
    container_name: angular-app
    hostname: angular-app
    image: flask-webserver-angular
    build:
      context: ../web-ui-applicazioni-indusriali
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - qdrant_bridge

# This network already exists and contains the qdrant container.
# The port to be selected is before the docker port-forwarding.
networks:
  qdrant_bridge:
    external: true